Script started on Tue 21 Oct 2014 09:27:20 PM PDT
~
hlao002@hammer $ cd CS100/rshell
~/CS100/rshell
hlao002@hammer $ bin/rshell
hlao002@hammer.cs.ucr.edu$ #begin testt ing
hlao002@hammer.cs.ucr.edu$ #test single commands
hlao002@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	README.md  src	test
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ echo cat
cat
hlao002@hammer.cs.ucr.edu$ mkdir
mkdir: missing operand
Try `mkdir --help' for more information.
hlao002@hammer.cs.ucr.edu$ cd
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$    pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$    pwd    pwd
pwd: ignoring non-option arguments
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ps
  PID TTY          TIME CMD
32814 pts/51   00:00:00 bash
32874 pts/51   00:00:00 rshell
33046 pts/51   00:00:00 ps
hlao002@hammer.cs.ucr.edu$ #testing single commands with argue ments
hlao002@hammer.cs.ucr.edu$ ls -a -l
total 36
drwx------ 6 hlao002 csmajs 4096 Oct 21 20:59 .
drwx------ 3 hlao002 csmajs 4096 Oct 21 19:37 ..
drwx------ 2 hlao002 csmajs 4096 Oct 21 21:26 bin
drwx------ 8 hlao002 csmajs 4096 Oct 21 20:40 .git
-rw------- 1 hlao002 csmajs  101 Oct 21 19:37 LICENSE
-rw------- 1 hlao002 csmajs  259 Oct 21 19:37 Makefile
-rw------- 1 hlao002 csmajs 3056 Oct 21 19:37 README.md
drwx------ 2 hlao002 csmajs 4096 Oct 21 20:26 src
drwx------ 2 hlao002 csmajs 4096 Oct 21 21:27 test
hlao002@hammer.cs.ucr.edu$ echo cats and dogs and chickens but not ducks
cats and dogs and chickens but not ducks
hlao002@hammer.cs.ucr.edu$ echo cats        and     d   d  o    o ggg g g gs
cats and d d o o ggg g g gs
hlao002@hammer.cs.ucr.edu$ mkdir pie
hlao002@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	pie  README.md	src  test
hlao002@hammer.cs.ucr.edu$ ls-  -0 a
.  ..  bin  .git  LICENSE  Makefile  pie  README.md  src  test
hlao002@hammer.cs.ucr.edu$ rm dir pie      ir pie
rm: cannot remove `dir': No such file or directory
rm: cannot remove `pie': Is a directory
hlao002@hammer.cs.ucr.edu$ rm dir pie          dir pie
hlao002@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	README.md  src	test
hlao002@hammer.cs.ucr.edu$ ls -a -a -a -a -a -a -a -a -a
.  ..  bin  .git  LICENSE  Makefile  README.md	src  test
hlao002@hammer.cs.ucr.edu$ #testing ";" connector
hlao002@hammer.cs.ucr.edu$ pwd ; mkdir
/home/csmajs/hlao002/CS100/rshell
mkdir: missing operand
Try `mkdir --help' for more information.
hlao002@hammer.cs.ucr.edu$ pwd ; ls
/home/csmajs/hlao002/CS100/rshell
bin  LICENSE  Makefile	README.md  src	test
hlao002@hammer.cs.ucr.edu$ ml   kdir echo ls ls2 ls3 ls4 ls5 ; ls ; d rmdir ls ls2 ls3 ls4 ls5 ; ls
bin  echo  LICENSE  ls	ls2  ls3  ls4  ls5  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ ls ; pwd
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ;s  ls; pwd
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ls ;pwd
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ls       ; pwd
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ls;
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ ;ls
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ ls ;;
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ ls ;; pwd
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ ;s -a;      ;s -a; make cakepies             echo cat and dogs
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ ls -a; mkdir fake; ls -a;    mkdir fake2;  ls -a;   mkdir fake3;rmdir fake1 fake       e fake2 fake3
.  ..  bin  echo  .git	LICENSE  Makefile  README.md  src  test
.  ..  bin  echo  fake	.git  LICENSE  Makefile  README.md  src  test
.  ..  bin  echo  fake	fake2  .git  LICENSE  Makefile	README.md  src	test
hlao002@hammer.cs.ucr.edu$      ls; pwd -a; pwdd; echo cat
bin  echo  LICENSE  Makefile  README.md  src  test
pwd: invalid option -- 'a'
Try `pwd --help' for more information.
execvp: No such file or directory
cat
hlao002@hammer.cs.ucr.edu$ djka ; jad
execvp: No such file or directory
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ bin/rshell
hlao002@hammer.cs.ucr.edu$ bin/rshell ; echo cat
hlao002@hammer.cs.ucr.edu$ exit
cat
hlao002@hammer.cs.ucr.edu$ exit
hlao002@hammer.cs.ucr.edu$ ;echo cat
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ echo cat ;; echo dog
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ ;;echo cat
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ #testing "&&" connectors
hlao002@hammer.cs.ucr.edu$ echo cat && echo dog
cat
dog
hlao002@hammer.cs.ucr.edu$ man pie && echo dog
No manual entry for pie
hlao002@hammer.cs.ucr.edu$ fail && echo dog
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ true && true
hlao002@hammer.cs.ucr.edu$ true && fail
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ man pie&& pwd
No manual entry for pie
hlao002@hammer.cs.ucr.edu$ man pie   &&  pwd
No manual entry for pie
hlao002@hammer.cs.ucr.edu$    man pie     &&                pwd
No manual entry for pie
hlao002@hammer.cs.ucr.edu$ ls  &&& p    pwd
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ls &&&           pwd
bin  echo  LICENSE  Makefile  README.md  src  test
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ ls && ls &&    ls    && ls   &&&ls      LS  ls &&&   ls && ls &&ls &&ls && man pie && pwd
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
No manual entry for pie
hlao002@hammer.cs.ucr.edu$ ls && fail echo cat and dogs
bin  echo  LICENSE  Makefile  README.md  src  test
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ && echo pie
bash: syntax error near unexpected token '&&'
hlao002@hammer.cs.ucr.edu$ echo pie &&
pie
hlao002@hammer.cs.ucr.edu$ echo pie && & &&
pie
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ echo pie && echo cat & &&&
pie
cat &
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ echo pie &&&&
bash: syntax error near unexpected token '&&'
hlao002@hammer.cs.ucr.edu$ echo cake &&
cake
hlao002@hammer.cs.ucr.edu$ bin/rshell && echo pig
hlao002@hammer.cs.ucr.edu$ exit
pig
hlao002@hammer.cs.ucr.edu$ #testing logic for "||" o connector
hlao002@hammer.cs.ucr.edu$ ls||pwd
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ echo cat | gods
cat | gods
hlao002@hammer.cs.ucr.edu$ echo cat|| dog
cat
hlao002@hammer.cs.ucr.edu$ cat   echo ||  dog

hlao002@hammer.cs.ucr.edu$ man pie |||||||
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ man pie || |||
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ man pie || echo dog
No manual entry for pie
dog
hlao002@hammer.cs.ucr.edu$ echo cakefail ||echo|skd
cakefail
hlao002@hammer.cs.ucr.edu$ echo cat|dog
cat|dog
hlao002@hammer.cs.ucr.edu$ ecs ho dog ||| dog
dog
hlao002@hammer.cs.ucr.edu$     \\\ || echo dog
execvp: No such file or directory
dog
hlao002@hammer.cs.ucr.edu$  || echo dog
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ breaksd
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ fail ||    echo cake
execvp: No such file or directory
cake
hlao002@hammer.cs.ucr.edu$ fail|| echo cake
execvp: No such file or directory
cake
hlao002@hammer.cs.ucr.edu$ fail || echo cake || echo pie
execvp: No such file or directory
cake
hlao002@hammer.cs.ucr.edu$ fail || fail || fail || fail ||| fail |||fail ||feils || ls || fail
execvp: No such file or directory
execvp: No such file or directory
execvp: No such file or directory
execvp: No such file or directory
execvp: No such file or directory
execvp: No such file or directory
execvp: No such file or directory
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ faill |||fail || echo cat
execvp: No such file or directory
execvp: No such file or directory
cat
hlao002@hammer.cs.ucr.edu$ || echo dog
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ ||dogs
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ dogs ||
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ echo cat || exit
cat
hlao002@hammer.cs.ucr.edu$ bin/rshell } || echo pie
hlao002@hammer.cs.ucr.edu$ exit
hlao002@hammer.cs.ucr.edu$ echo pie || bin/rshell
pie
hlao002@hammer.cs.ucr.edu$ man pie || bin/rshell
No manual entry for pie
hlao002@hammer.cs.ucr.edu$ exit
hlao002@hammer.cs.ucr.edu$ #testing exit
hlao002@hammer.cs.ucr.edu$ ;exit
bash: syntax error near unexpected token ';'
hlao002@hammer.cs.ucr.edu$ exit ;
~/CS100/rshell
hlao002@hammer $ bin/rshell
hlao002@hammer.cs.ucr.edu$ echo cat || exit
cat
hlao002@hammer.cs.ucr.edu$ echo cat && exit
cat
~/CS100/rshell
hlao002@hammer $ bin/rshell
hlao002@hammer.cs.ucr.edu$ echo cat; exit
cat
~/CS100/rshell
hlao002@hammer $ bin./[K[K/rshell
hlao002@hammer.cs.ucr.edu$ echo exit
exit
hlao002@hammer.cs.ucr.edu$ exitdhskdelds
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ cat || exit
^C
~/CS100/rshell
hlao002@hammer $ bin/rshell
hlao002@hammer.cs.ucr.edu$ || || || ||| ls || pwd
bash: syntax error near unexpected token '||'
hlao002@hammer.cs.ucr.edu$ echo exit exz it exit
exit exit exit
hlao002@hammer.cs.ucr.edu$ echo exit && mkdir exit && ls && rmdir exit && ls
exit
bin  echo  exit  LICENSE  Makefile  README.md  src  test
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ EXIT
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ #testing comments
hlao002@hammer.cs.ucr.edu$ ls &&#hello im pie
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ ls || echo cat#dog
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ echo d cat#dog
cat
hlao002@hammer.cs.ucr.edu$ fail || #echo cat
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ #&&echo cat
hlao002@hammer.cs.ucr.edu$ #   **  && echo cat # &&
bash: syntax error near unexpected token '&&'
hlao002@hammer.cs.ucr.edu$ ls ## comendsjdeks
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ ls && e pwd && # pesidsde
bin  echo  LICENSE  Makefile  README.md  src  test
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ ls # exit # exit # ####
bin  echo  LICENSE  Makefile  README.md  src  test
hlao002@hammer.cs.ucr.edu$ #testing multiple connector types on same commdn  and (priority h behavior listed in READM>E  E> .md)
hlao002@hammer.cs.ucr.edu$ echo cat && echo dog ; echo cat and echskds
cat && echo dog
cat and echskds
hlao002@hammer.cs.ucr.edu$ pwd && ls  lse  && echo cat ; echo dog
pwd: ignoring non-option arguments
/home/csmajs/hlao002/CS100/rshell
dog
hlao002@hammer.cs.ucr.edu$ echo cat ; echo cat || echo cat
cat
cat || echo cat
hlao002@hammer.cs.ucr.edu$ echo dog ; echo cat ||             ech   man pie || echo cat ||  && echo b dog
dog
No manual entry for pie
No manual entry for ||
7[?47h[?1h=ECHO(1)                          User Commands                         ECHO(1)

[1mNAME[m
       echo - display a line of text

[1mSYNOPSIS[m
       [1mecho[m [[4mSHORT-OPTION[m]... [[4mSTRING[m]...
       [1mecho[m [4mLONG-OPTION[m

[1mDESCRIPTION[m
       Echo the STRING(s) to standard output.

       [1m-n[m     do not output the trailing newline

       [1m-e[m     enable interpretation of backslash escapes

       [1m-E[m     disable interpretation of backslash escapes (default)

       [1m--help[m display this help and exit

       [1m--version[m
              output version information and exit

       If [1m-e[m is in effect, the following sequences are recognized:

       \\     backslash

       \a     alert (BEL)

       \b     backspace

       \c     produce no further output

       \e     escape

       \f     form feed

       \n     new line

       \r     carriage return

       \t     horizontal tab

       \v     vertical tab

       \0NNN  byte with octal value NNN (1 to 3 digits)

       \xHH   byte with hexadecimal value HH (1 to 2 digits)

       NOTE: your shell may have its own version of echo, which usually supersedes the version described here.  Please refer to your shell’s documentation for details about the options
       it supports.

[1mAUTHOR[m
       Written by Brian Fox and Chet Ramey.

[1mREPORTING[m [1mBUGS[m
       Report echo bugs to bug-coreutils@gnu.org
:[K[K[?1l>[2J[?47l87[?47h[?1h=CAT(1)                           User Commands                          CAT(1)

[1mNAME[m
       cat - concatenate files and print on the standard output

[1mSYNOPSIS[m
       [1mcat[m [[4mOPTION[m]... [[4mFILE[m]...

[1mDESCRIPTION[m
       Concatenate FILE(s), or standard input, to standard output.

       [1m-A[m, [1m--show-all[m
              equivalent to [1m-vET[m

       [1m-b[m, [1m--number-nonblank[m
              number nonempty output lines

       [1m-e[m     equivalent to [1m-vE[m

       [1m-E[m, [1m--show-ends[m
              display $ at end of each line

       [1m-n[m, [1m--number[m
              number all output lines

       [1m-s[m, [1m--squeeze-blank[m
              suppress repeated empty output lines

       [1m-t[m     equivalent to [1m-vT[m

       [1m-T[m, [1m--show-tabs[m
              display TAB characters as ^I

       [1m-u[m     (ignored)

       [1m-v[m, [1m--show-nonprinting[m
              use ^ and M- notation, except for LFD and TAB

       [1m--help[m display this help and exit

       [1m--version[m
              output version information and exit

       With no FILE, or when FILE is -, read standard input.

[1mEXAMPLES[m
       cat f - g
              Output f’s contents, then standard input, then g’s contents.

       cat    Copy standard input to standard output.

[1mAUTHOR[m
       Written by Torbjorn Granlund and Richard M. Stallman.

[1mREPORTING[m [1mBUGS[m
       Report cat bugs to bug-coreutils@gnu.org
       GNU coreutils home page: <http://www.gnu.org/software/coreutils/>
:[K[K[?1l>[2J[?47l8No manual entry for &&
7[?47h[?1h=ECHO(1)                          User Commands                         ECHO(1)

[1mNAME[m
       echo - display a line of text

[1mSYNOPSIS[m
       [1mecho[m [[4mSHORT-OPTION[m]... [[4mSTRING[m]...
       [1mecho[m [4mLONG-OPTION[m

[1mDESCRIPTION[m
       Echo the STRING(s) to standard output.

       [1m-n[m     do not output the trailing newline

       [1m-e[m     enable interpretation of backslash escapes

       [1m-E[m     disable interpretation of backslash escapes (default)

       [1m--help[m display this help and exit

       [1m--version[m
              output version information and exit

       If [1m-e[m is in effect, the following sequences are recognized:

       \\     backslash

       \a     alert (BEL)

       \b     backspace

       \c     produce no further output

       \e     escape

       \f     form feed

       \n     new line

       \r     carriage return

       \t     horizontal tab

       \v     vertical tab

       \0NNN  byte with octal value NNN (1 to 3 digits)

       \xHH   byte with hexadecimal value HH (1 to 2 digits)

       NOTE: your shell may have its own version of echo, which usually supersedes the version described here.  Please refer to your shell’s documentation for details about the options
       it supports.

[1mAUTHOR[m
       Written by Brian Fox and Chet Ramey.

[1mREPORTING[m [1mBUGS[m
       Report echo bugs to bug-coreutils@gnu.org
:[K[K[?1l>[2J[?47l8No manual entry for dog
hlao002@hammer.cs.ucr.edu$ echo dog && echo cat || do  echo dog
dog
cat || echo dog
hlao002@hammer.cs.ucr.edu$ bin/rshell && bin  .rshell && bin..rshell
hlao002@hammer.cs.ucr.edu$ exit
execvp: No such file or directory
hlao002@hammer.cs.ucr.edu$ bin/rshell && echo first && bin  /rshell && echoi    second
hlao002@hammer.cs.ucr.edu$ exit
first
hlao002@hammer.cs.ucr.edu$ exit
second
hlao002@hammer.cs.ucr.edu$ echo LEAVING     leaving rshell
LEAVING leaving rshell
hlao002@hammer.cs.ucr.edu$ #condl  cludes testing
hlao002@hammer.cs.ucr.edu$ exit
~/CS100/rshell
hlao002@hammer $ exit
exit

Script done on Tue 21 Oct 2014 10:39:45 PM PDT
