Script started on Fri 05 Dec 2014 06:34:17 PM PST
~
hlao002@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.                               |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mhlao002[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m bin/[K[K[K[Kcd CS100/rshell
[s%%%%%%%%%%[u[0;32mhlao002[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m valgrind --leak-check=yes bin/rshell
==48321== Memcheck, a memory error detector
==48321== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==48321== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==48321== Command: bin/rshell
==48321== 
hlao002@hammer.cs.ucr.edu$ ls -l a
==48321== Invalid write of size 1
==48321==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==48321==    by 0x403931: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c330c2 is 0 bytes after a block of size 2 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48329== Invalid read of size 1
==48329==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==48329==    by 0x3059C9CF1F: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48329==    by 0x402A93: runExecvp(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x402E49: piping(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403B2D: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==  Address 0x4c330c2 is 0 bytes after a block of size 2 alloc'd
==48329==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48329==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329== 
==48329== Syscall param execve(argv[i]) points to unaddressable byte(s)
==48329==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==48329==    by 0x402B4F: runExecvp(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x402E49: piping(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403B2D: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==  Address 0x4c330c2 is 0 bytes after a block of size 2 alloc'd
==48329==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48329==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48329== 
.  ..  bin  .git  LICENSE  Makefile  README.md	src  test
==48321== Mismatched free() / delete / delete []
==48321==    at 0x4A06016: operator delete(void*) (vg_replace_malloc.c:480)
==48321==    by 0x403C0A: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c33000 is 0 bytes inside a block of size 24 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x403860: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
hlao002@hammer.cs.ucr.edu$ echo cat
==48321== Invalid write of size 1
==48321==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==48321==    by 0x403931: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c38194 is 0 bytes after a block of size 4 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48330== Invalid read of size 1
==48330==    at 0x4A07FC4: __GI_strlen (mc_replace_strmem.c:404)
==48330==    by 0x3059C9CF1F: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48330==    by 0x402A93: runExecvp(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x402E49: piping(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403B2D: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==  Address 0x4c38194 is 0 bytes after a block of size 4 alloc'd
==48330==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48330==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330== 
==48330== Syscall param execve(argv[i]) points to unaddressable byte(s)
==48330==    at 0x30508ACDA7: execve (in /lib64/libc-2.12.so)
==48330==    by 0x402B4F: runExecvp(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x402E49: piping(char**, int, int, char) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403B2D: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==  Address 0x4c38194 is 0 bytes after a block of size 4 alloc'd
==48330==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48330==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48330== 
cat
==48321== Mismatched free() / delete / delete []
==48321==    at 0x4A06016: operator delete(void*) (vg_replace_malloc.c:480)
==48321==    by 0x403C0A: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c380d0 is 0 bytes inside a block of size 24 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x403860: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
hlao002@hammer.cs.ucr.edu$ exit
==48321== Invalid write of size 1
==48321==    at 0x4A080CF: __GI_strcpy (mc_replace_strmem.c:443)
==48321==    by 0x403931: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c3d0c4 is 0 bytes after a block of size 4 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== Invalid read of size 1
==48321==    at 0x4A08538: __GI_strcmp (mc_replace_strmem.c:730)
==48321==    by 0x4039E6: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==  Address 0x4c3d0c4 is 0 bytes after a block of size 4 alloc'd
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 
==48321== HEAP SUMMARY:
==48321==     in use at exit: 554 bytes in 26 blocks
==48321==   total heap usage: 133 allocs, 107 frees, 64,471 bytes allocated
==48321== 
==48321== 4 bytes in 2 blocks are definitely lost in loss record 2 of 19
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 7 bytes in 2 blocks are definitely lost in loss record 3 of 19
==48321==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48321==    by 0x4038FA: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 8 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034C7: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 9 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034E5: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 10 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034C7: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 11 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034E5: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 12 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034C7: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 26 bytes in 1 blocks are possibly lost in loss record 13 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CDE4: ??? (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9CF32: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x404292: boost::char_separator<char, std::char_traits<char> >::char_separator(char const*, char const*, boost::empty_token_policy) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4034E5: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 29 bytes in 1 blocks are possibly lost in loss record 14 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D19A: std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D5EB: std::string::reserve(unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C7BFF4: std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4031E0: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 33 bytes in 1 blocks are possibly lost in loss record 15 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D19A: std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D5EB: std::string::reserve(unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C7BFF4: std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4031E0: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 33 bytes in 1 blocks are possibly lost in loss record 16 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D19A: std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9D5EB: std::string::reserve(unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C7BFF4: std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4031E0: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403C0F: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403E6F: main (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 55 bytes in 2 blocks are possibly lost in loss record 17 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DDA9: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DF6B: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9E947: std::string::replace(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4059FF: std::string& std::string::assign<__gnu_cxx::__normal_iterator<char const*, std::string> >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4058C4: void boost::tokenizer_detail::assign_or_plus_equal<std::random_access_iterator_tag>::assign<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4055C0: bool boost::char_separator<char, std::char_traits<char> >::operator()<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>&, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x405662: boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::increment() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404F91: void boost::iterator_core_access::increment<boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string> >(boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404ACF: boost::iterator_facade<boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>, std::string, boost::forward_traversal_tag, std::string const&, long>::operator++() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4044D6: boost::detail::postfix_increment_result<boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>, std::string, std::string const&, boost::forward_traversal_tag>::type boost::operator++<boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>, std::string, boost::forward_traversal_tag, std::string const&, long>(boost::iterator_facade<boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>, std::string, boost::forward_traversal_tag, std::string const&, long>&, int) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 85 bytes in 3 blocks are possibly lost in loss record 18 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DDA9: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DF6B: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9E947: std::string::replace(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4059FF: std::string& std::string::assign<__gnu_cxx::__normal_iterator<char const*, std::string> >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4058C4: void boost::tokenizer_detail::assign_or_plus_equal<std::random_access_iterator_tag>::assign<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4055C0: bool boost::char_separator<char, std::char_traits<char> >::operator()<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>&, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404ECE: boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::initialize() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404A51: boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::token_iterator(boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4043C0: boost::tokenizer<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::begin() const (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x40351E: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== 92 bytes in 3 blocks are possibly lost in loss record 19 of 19
==48321==    at 0x4A075FC: operator new(unsigned long) (vg_replace_malloc.c:298)
==48321==    by 0x3059C9C3C8: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DDA9: std::string::_M_mutate(unsigned long, unsigned long, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9DF6B: std::string::_M_replace_safe(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x3059C9E947: std::string::replace(unsigned long, unsigned long, char const*, unsigned long) (in /usr/lib64/libstdc++.so.6.0.13)
==48321==    by 0x4059FF: std::string& std::string::assign<__gnu_cxx::__normal_iterator<char const*, std::string> >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4058C4: void boost::tokenizer_detail::assign_or_plus_equal<std::random_access_iterator_tag>::assign<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4055C0: bool boost::char_separator<char, std::char_traits<char> >::operator()<__gnu_cxx::__normal_iterator<char const*, std::string>, std::string>(__gnu_cxx::__normal_iterator<char const*, std::string>&, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string&) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404ECE: boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::initialize() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x404A51: boost::token_iterator<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::token_iterator(boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>) (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x4043C0: boost::tokenizer<boost::char_separator<char, std::char_traits<char> >, __gnu_cxx::__normal_iterator<char const*, std::string>, std::string>::begin() const (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321==    by 0x403754: bash() (in /home/csmajs/hlao002/CS100/rshell/bin/rshell)
==48321== 
==48321== LEAK SUMMARY:
==48321==    definitely lost: 11 bytes in 4 blocks
==48321==    indirectly lost: 0 bytes in 0 blocks
==48321==      possibly lost: 483 bytes in 17 blocks
==48321==    still reachable: 60 bytes in 5 blocks
==48321==         suppressed: 0 bytes in 0 blocks
==48321== Reachable blocks (those to which a pointer was found) are not shown.
==48321== To see them, rerun with: --leak-check=full --show-reachable=yes
==48321== 
==48321== For counts of detected and suppressed errors, rerun with: -v
==48321== ERROR SUMMARY: 22 errors from 20 contexts (suppressed: 6 from 6)
[s%%%%%%%%%%[u[0;32mhlao002[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m bin/rshell
hlao002@hammer.cs.ucr.edu$ #testing Path     ATH vai ri iable
hlao002@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	README.md  src	test
hlao002@hammer.cs.ucr.edu$ ls -l
total 32
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:27 bin
-rw------- 1 hlao002 csmajs  101 Dec  5 18:05 LICENSE
-rw------- 1 hlao002 csmajs  630 Dec  5 18:05 Makefile
-rw------- 1 hlao002 csmajs 8406 Dec  5 18:05 README.md
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:20 src
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:32 test
hlao002@hammer.cs.ucr.edu$ ls -l ; echo cat
total 32
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:27 bin
-rw------- 1 hlao002 csmajs  101 Dec  5 18:05 LICENSE
-rw------- 1 hlao002 csmajs  630 Dec  5 18:05 Makefile
-rw------- 1 hlao002 csmajs 8406 Dec  5 18:05 README.md
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:20 src
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:32 test
cat
hlao002@hammer.cs.ucr.edu$ ls-l      -l;  echo cat
total 32
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:27 bin
-rw------- 1 hlao002 csmajs  101 Dec  5 18:05 LICENSE
-rw------- 1 hlao002 csmajs  630 Dec  5 18:05 Makefile
-rw------- 1 hlao002 csmajs 8406 Dec  5 18:05 README.md
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:20 src
drwx------ 2 hlao002 csmajs 4096 Dec  5 18:32 test
cat
hlao002@hammer.cs.ucr.edu$ #testing n false command
hlao002@hammer.cs.ucr.edu$ fake
access: No such file or directory
hlao002@hammer.cs.ucr.edu$ fake cat
access: No such file or directory
hlao002@hammer.cs.ucr.edu$ echo cat
cat
hlao002@hammer.cs.ucr.edu$ #testing cd
hlao002@hammer.cs.ucr.edu$ cd
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002
hlao002@hammer.cs.ucr.edu$ cd CS100/rshell
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ cd .
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ cd ..
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100
hlao002@hammer.cs.ucr.edu$ cd .. pie
Error: Incorrect syntax, cd only accepts a maximum of 1 parameter.
hlao002@hammer.cs.ucr.edu$ cd ; cd CS100
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100
hlao002@hammer.cs.ucr.edu$ cd ; cd rshell
chdir: No such file or directory
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002
hlao002@hammer.cs.ucr.edu$ cd CS100/rshel  l && echo cat
cat
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ cd ./test
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell/test
hlao002@hammer.cs.ucr.edu$ cd ..
hlao002@hammer.cs.ucr.edu$ pwd
/home/csmajs/hlao002/CS100/rshell
hlao002@hammer.cs.ucr.edu$ #testing ^C signal
hlao002@hammer.cs.ucr.edu$ cat
^Chlao002@hammer.cs.ucr.edu$ ^C
hlao002@hammer.cs.ucr.edu$ ^C
hlao002@hammer.cs.ucr.edu$ wc
^Chlao002@hammer.cs.ucr.edu$ wc  ech ca   o cat ; wc
cat
^Chlao002@hammer.cs.ucr.edu$ @ #testing pip     concluded
hlao002@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32mhlao002[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m exit
exit
~
hlao002@hammer $ exit
exit

Script done on Fri 05 Dec 2014 06:41:23 PM PST
